
package ec.edu.ups.evabedoyamanuel.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:09:24.254-05:00
 * Generated source version: 3.5.0
 */

@WebFault(name = "Exception", targetNamespace = "http://services.EVAbedoyamanuel.ups.edu.ec/")
public class Exception_Exception extends java.lang.Exception {

    private ec.edu.ups.evabedoyamanuel.services.Exception faultInfo;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, ec.edu.ups.evabedoyamanuel.services.Exception exception) {
        super(message);
        this.faultInfo = exception;
    }

    public Exception_Exception(String message, ec.edu.ups.evabedoyamanuel.services.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = exception;
    }

    public ec.edu.ups.evabedoyamanuel.services.Exception getFaultInfo() {
        return this.faultInfo;
    }
}
