package ec.edu.ups.evabedoyamanuel.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:09:24.259-05:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://services.EVAbedoyamanuel.ups.edu.ec/", name = "LibroServicesSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface LibroServicesSOAP {

    @WebMethod
    @RequestWrapper(localName = "getlibros", targetNamespace = "http://services.EVAbedoyamanuel.ups.edu.ec/", className = "ec.edu.ups.evabedoyamanuel.services.Getlibros")
    @ResponseWrapper(localName = "getlibrosResponse", targetNamespace = "http://services.EVAbedoyamanuel.ups.edu.ec/", className = "ec.edu.ups.evabedoyamanuel.services.GetlibrosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ec.edu.ups.evabedoyamanuel.services.Libro> getlibros()
;

    @WebMethod
    @RequestWrapper(localName = "crearlibro", targetNamespace = "http://services.EVAbedoyamanuel.ups.edu.ec/", className = "ec.edu.ups.evabedoyamanuel.services.Crearlibro")
    @ResponseWrapper(localName = "crearlibroResponse", targetNamespace = "http://services.EVAbedoyamanuel.ups.edu.ec/", className = "ec.edu.ups.evabedoyamanuel.services.CrearlibroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearlibro(

        @WebParam(name = "arg0", targetNamespace = "")
        ec.edu.ups.evabedoyamanuel.services.Libro arg0
    ) throws Exception_Exception;
}
