
package ec.edu.ups.evabedoyamanuel.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:09:24.185-05:00
 * Generated source version: 3.5.0
 *
 */
public final class LibroServicesSOAP_LibroServicesSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.EVAbedoyamanuel.ups.edu.ec/", "LibroServicesSOAPService");
    
    private LibroServicesSOAP_LibroServicesSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LibroServicesSOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LibroServicesSOAPService ss = new LibroServicesSOAPService(wsdlURL, SERVICE_NAME);
        LibroServicesSOAP port = ss.getLibroServicesSOAPPort();
/*
        {
        System.out.println("Invoking getlibros...");
        java.util.List<ec.edu.ups.evabedoyamanuel.services.Libro> libros = port.getlibros();
        System.out.println("getlibros.result=" + libros);


        }
        
        /*{
        System.out.println("Invoking crearlibro...");
        ec.edu.ups.evabedoyamanuel.services.Libro libros = null;
        libros = new Libro();
        libros.setCodigo(7);
        libros.setAutor("Miguel de cervantes");
        libros.setEdicion("5");
        libros.setTitulo("El quijote");
        try {
            java.lang.String _crearlibro__return = port.crearlibro(libros);
            System.out.println("crearlibro.result=" + _crearlibro__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }*/

        System.exit(0);
    }

}
