package ec.edu.ups.evabedoyamanuel.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T12:09:24.265-05:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "LibroServicesSOAPService",
                  wsdlLocation = "http://localhost:8080/EvaBedoyamanuel/LibroServicesSOAP?wsdl",
                  targetNamespace = "http://services.EVAbedoyamanuel.ups.edu.ec/")
public class LibroServicesSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.EVAbedoyamanuel.ups.edu.ec/", "LibroServicesSOAPService");
    public final static QName LibroServicesSOAPPort = new QName("http://services.EVAbedoyamanuel.ups.edu.ec/", "LibroServicesSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/EvaBedoyamanuel/LibroServicesSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LibroServicesSOAPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/EvaBedoyamanuel/LibroServicesSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LibroServicesSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LibroServicesSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibroServicesSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LibroServicesSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LibroServicesSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LibroServicesSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LibroServicesSOAP
     */
    @WebEndpoint(name = "LibroServicesSOAPPort")
    public LibroServicesSOAP getLibroServicesSOAPPort() {
        return super.getPort(LibroServicesSOAPPort, LibroServicesSOAP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibroServicesSOAP
     */
    @WebEndpoint(name = "LibroServicesSOAPPort")
    public LibroServicesSOAP getLibroServicesSOAPPort(WebServiceFeature... features) {
        return super.getPort(LibroServicesSOAPPort, LibroServicesSOAP.class, features);
    }

}
